export const dashboardMeta = {
  title: "鸿运集团增长看板",
  version: "V0.1",
  updatedAt: "2026-06-26",
  owner: "周树权",
  coreGoals: ["提升品牌知名度", "提升万宁渠道销量", "推动线上电商增长"]
};

export const dashboardKpis = {
  totalInvestment: 124010,
  totalNotes: 85,
  totalExposure: 2007286,
  totalReads: 372902,
  totalInteractions: 29033
};

export const focusProjects = [
  {
    id: "bull-fengtongling",
    brandGroup: "公牛牌",
    name: "公牛牌风痛灵",
    shortGoal: "通过小红书种草与投流放大，提升品牌搜索和万宁渠道销售转化。",
    status: "yellow",
    statusText: "待推进/有风险",
    stage: "6月-7月第三批种草推进中，投流资质认证待完善",
    owner: "周树权",
    investment: 106780,
    notes: 61,
    videos: null,
    exposure: 1704401,
    reads: 318922,
    interactions: 24426,
    search90d: 3109,
    searchGrowth90d: "+638.99%",
    taobaoSearch: "待补充",
    taobaoSalesGrowth30d: "待补充",
    manningSalesGrowth90d: "待补充",
    weeklyResult: "已完成5月种草，6-7月两轮种草，累计形成61篇内容资产。",
    completed: ["5月 Agency 种草", "6-7月两轮达人种草", "61篇小红书内容资产"],
    currentResult: "累计曝光1,704,401；累计阅读318,922；累计互动24,426；近90天品牌搜索量3,109。",
    risk: "聚光投流资质未完成，影响投流启动和投放效果最大化。",
    next: "准备康活健独家授权公牛牌销售授权书、康活健食品厂谷歌地图认证，补齐资质后提交投流认证。",
    bossSupport: "确认投流资质与6月-7月第一批水下笔记达人费用结算。",
    background: "公牛牌风痛灵当前已完成多轮种草，下一阶段重点是补齐投流资质，将已有内容资产放大到品牌搜索和万宁销售转化。",
    path: ["小红书种草", "提升品牌知名度", "香港游客/本地用户", "万宁购买", "销量增长"],
    costItems: [
      { name: "5月 Agency 种草", amount: 62040 },
      { name: "6-7月 第一~三批达人", amount: 44740 }
    ],
    contentProgress: [
      { label: "小红书笔记", value: "61篇" },
      { label: "投流状态", value: "资质认证待完善" },
      { label: "品牌搜索", value: "近90天3,109" },
      { label: "淘宝搜索人气值", value: "待补充" },
      { label: "万宁销量环比", value: "待补充" }
    ],
    plan: ["补齐销售授权书", "完成康活健食品厂谷歌地图认证", "提交聚光投流认证", "启动投流测试并观察搜索/销售反馈"]
  },
  {
    id: "jzt-huoluo-oil",
    brandGroup: "济众堂",
    name: "济众堂百步追风活络油",
    shortGoal: "提升万宁渠道销量，维持万宁渠道合作。",
    status: "yellow",
    statusText: "待推进/有风险",
    stage: "万宁销量考核 + 推广场景测试",
    owner: "周树权",
    investment: 17230,
    notes: 24,
    videos: null,
    exposure: 302885,
    reads: 53980,
    interactions: 4607,
    search90d: 1423,
    searchGrowth90d: "+22.83%",
    taobaoSearch: "待补充",
    taobaoSalesGrowth30d: "待补充",
    manningSalesGrowth90d: "待补充",
    weeklyResult: "已恢复万宁上架，进入月销10万元渠道考核阶段。",
    completed: ["恢复万宁上架", "24篇小红书笔记", "推广场景测试"],
    currentResult: "累计曝光302,885；累计阅读53,980；累计互动4,607；近90天品牌搜索量1,423。",
    risk: "未来仍有每月10万元销售压力，未达标仍有再次下架风险。",
    next: "万宁资源谈判。如果没有资源，评估是否推进100篇万宁笔记及30条抖音短视频做资源资格；如按该量级执行，需要增加人力支持。",
    bossSupport: "推进万宁推广资源、广告位资源、其他渠道资源。",
    background: "百步追风活络油当前核心是通过内容种草支持万宁渠道动销，争取万宁资源，降低再次下架风险。",
    path: ["小红书种草", "提升品牌知名度", "香港游客/本地用户", "万宁购买", "销量增长"],
    listingPlan: ["恢复上架", "月销10万元考核", "小红书种草", "万宁资源谈判", "渠道销量增长"],
    manningProgress: [
      { label: "恢复上架", value: "已完成" },
      { label: "月销目标", value: "10万元" },
      { label: "万宁资源沟通", value: "推进中" },
      { label: "销量反馈机制", value: "待建立" }
    ],
    plan: ["推进万宁资源谈判", "确认是否执行100篇万宁笔记", "确认是否执行30条抖音短视频", "建立万宁销量数据反馈机制"]
  },
  {
    id: "jzt-health-food",
    brandGroup: "济众堂",
    name: "济众堂保健食品：肝轻松、眼清清",
    shortGoal: "推动保健食品上市，建立线上电商增长路径。",
    status: "red",
    statusText: "高风险/需支持",
    stage: "包装设计已完成，开始生产50件",
    owner: "周树权",
    investment: null,
    notes: null,
    videos: null,
    exposure: null,
    reads: null,
    interactions: null,
    weeklyResult: "肝轻松、眼清清包装确定；产品配方已完成；小红书店铺承接方案初步评估。",
    completed: ["肝轻松、眼清清包装确定", "产品配方已完成", "小红书店铺承接方案初步评估", "开始生产50件"],
    currentResult: "产品基础已完成，上市路径和市场策略尚未完整建立。",
    risk: "产品香港相关资质、内地产品备案、产品资质、社媒报白资料、市场分析、产品定价、售卖渠道、产品宣传、电商运营策略未完成。",
    next: "推进资质确认、定价策略、电商渠道、产品推广、正式上市规划。",
    bossSupport: "确认保健食品项目优先级，并支持资质与上市路径推进。",
    background: "保健食品项目是济众堂未来线上电商增长的重要机会，目前重点是补齐上市资料和销售链路。",
    products: ["肝轻松", "眼清清"],
    launchFlow: ["资质确认", "定价策略", "电商渠道", "内容种草", "投流测试", "正式上市"],
    healthPath: ["产品上市", "小红书种草", "品牌笔记带货/达播/店播带货", "渠道购买"],
    plan: ["确认香港相关资质", "推进内地产品备案和社媒报白", "确认定价与活动策略", "搭建电商渠道和运营策略"]
  }
];

export const overviewProjects = [
  ...focusProjects,
  {
    id: "jzt-brand",
    brandGroup: "济众堂",
    name: "济众堂品牌运营",
    shortGoal: "沉淀济众堂品牌内容资产，提升品牌认知。",
    status: "green",
    statusText: "进展顺利",
    stage: "品牌运营",
    owner: "周树权",
    investment: null,
    notes: null,
    videos: null,
    exposure: null,
    reads: null,
    interactions: null,
    completed: ["品牌内容持续沉淀"],
    currentResult: "近90天品牌搜索量1,423；近90天品牌搜索环比22.83%。",
    risk: "销量和电商数据反馈机制待建立。",
    next: "继续沉淀品牌内容资产，建立数据反馈机制。",
    bossSupport: "待补充"
  },
  {
    id: "bull-brand",
    brandGroup: "公牛牌",
    name: "公牛牌品牌运营",
    shortGoal: "承接风痛灵种草效果，提升公牛牌品牌搜索。",
    status: "yellow",
    statusText: "待推进/有风险",
    stage: "品牌运营",
    owner: "周树权",
    investment: null,
    notes: null,
    videos: null,
    exposure: null,
    reads: null,
    interactions: null,
    completed: ["品牌搜索数据已跟踪"],
    currentResult: "近90天品牌搜索量3,109；近90天品牌搜索环比638.99%。",
    risk: "投流资质未完成，影响放大效率。",
    next: "结合风痛灵投流认证继续推进。",
    bossSupport: "投流资质支持"
  }
];

export const brandAccounts = [
  {
    brand: "济众堂",
    name: "香港济众堂 - 小红书",
    url: "https://www.xiaohongshu.com/user/profile/667b67da0000000007004f85"
  },
  {
    brand: "公牛牌",
    name: "香港公牛牌 - 小红书",
    url: "https://www.xiaohongshu.com/user/profile/682ec7db000000000e01f1c9?xsec_token=AB_GPraoW3NIgpmfLFEWLVJZGLalvto5ZAumIa4haVxl0=&xsec_source=pc_search"
  }
];

export const creatorAssets = [
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "跳跳猪小姐",
    "title": "跳跳猪小姐｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9xLjZPpy0iN",
    "cost": 1501,
    "exposure": 12420,
    "reads": 3565,
    "interactions": 237,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "卡罗琳的生活日志",
    "title": "卡罗琳的生活日志｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/4Bt29InZziJ",
    "cost": 1505,
    "exposure": 13039,
    "reads": 1365,
    "interactions": 148,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "醒目嘟崽",
    "title": "醒目嘟崽｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/AUxA0e2JG4g",
    "cost": 1288,
    "exposure": 11199,
    "reads": 1269,
    "interactions": 139,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "全糖可乐加冰",
    "title": "全糖可乐加冰｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/L5if2yzfoQ",
    "cost": 1007,
    "exposure": 58536,
    "reads": 6662,
    "interactions": 319,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "Ava系包包大人",
    "title": "Ava系包包大人｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/2Pdud61S2rV",
    "cost": 1005,
    "exposure": 9134,
    "reads": 1696,
    "interactions": 156,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "南方姑凉",
    "title": "南方姑凉｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/4MPurov64lz",
    "cost": 1054,
    "exposure": 2556,
    "reads": 238,
    "interactions": 195,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "山竹呀（合集）",
    "title": "山竹呀（合集）｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/56Fu17xQUQ6",
    "cost": 1000,
    "exposure": 45078,
    "reads": 1790,
    "interactions": 413,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "香辣肉谢堡",
    "title": "香辣肉谢堡｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/As7SBRpPPdb",
    "cost": 1052,
    "exposure": 42049,
    "reads": 2859,
    "interactions": 368,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "小潘同学（医学生版）",
    "title": "小潘同学（医学生版）｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9jvrMjdPfh3",
    "cost": 6665,
    "exposure": 6579,
    "reads": 2318,
    "interactions": 275,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "养生达人爱爱",
    "title": "养生达人爱爱｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/7W8ouPnwSHB",
    "cost": 7182,
    "exposure": 67437,
    "reads": 8428,
    "interactions": 1785,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "桑桑自律养生",
    "title": "桑桑自律养生｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/4P5tFUtyYWN",
    "cost": 6686,
    "exposure": 20887,
    "reads": 3018,
    "interactions": 488,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "橙子养生记",
    "title": "橙子养生记｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/1iWeoxLfG8B",
    "cost": 6194,
    "exposure": 17072,
    "reads": 2626,
    "interactions": 421,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "小1的逛吃手册",
    "title": "小1的逛吃手册｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/AfP4piy96lb",
    "cost": 6814,
    "exposure": 3422,
    "reads": 589,
    "interactions": 106,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "许如意CC",
    "title": "许如意CC｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/6iUOhHOggG6",
    "cost": 1500,
    "exposure": 15302,
    "reads": 6183,
    "interactions": 201,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "kuromi🍨",
    "title": "kuromi🍨｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/5FTZ1K1PvWa",
    "cost": 1500,
    "exposure": 18213,
    "reads": 4521,
    "interactions": 238,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "差点4美女",
    "title": "差点4美女｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9M6wLm7culP",
    "cost": 1542,
    "exposure": 24202,
    "reads": 2692,
    "interactions": 514,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "素颜小筑",
    "title": "素颜小筑｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/6veQvXhwTBz",
    "cost": 1506,
    "exposure": 24607,
    "reads": 2399,
    "interactions": 380,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "区KK",
    "title": "区KK｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/69f05dd40000000038021e95?source=webshare&xhsshare=pc_web&xsec_token=CBthoB7K6xDVMWjm0K024Xtnsb8-haWidJkWYVKUyxv8M=&xsec_source=pc_share",
    "cost": 2577,
    "exposure": 268,
    "reads": 74,
    "interactions": 27,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "WOW Jenny",
    "title": "WOW Jenny｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/3m9zVI6rNW5",
    "cost": 1504,
    "exposure": 24091,
    "reads": 2133,
    "interactions": 186,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "是子淇呀💡疲惫版",
    "title": "是子淇呀💡疲惫版｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/1WH6zTBaCZk",
    "cost": 1576,
    "exposure": 22424,
    "reads": 2141,
    "interactions": 158,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "老爱同学爱养生",
    "title": "老爱同学爱养生｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/AyZfn8xURV4",
    "cost": 1500,
    "exposure": 436,
    "reads": 1232,
    "interactions": 62,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "一颗小土豆",
    "title": "一颗小土豆｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/7SAhKNZcpQQ",
    "cost": 1500,
    "exposure": 3128,
    "reads": 72,
    "interactions": 61,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "静心养生",
    "title": "静心养生｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/8F2dVkn6t9L",
    "cost": 1009,
    "exposure": 7568,
    "reads": 726,
    "interactions": 45,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "快到我婉里来",
    "title": "快到我婉里来｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9Mlgi14CGaz",
    "cost": 1240,
    "exposure": 1006,
    "reads": 149,
    "interactions": 132,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "与Jerry童行",
    "title": "与Jerry童行｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/6L4TqPxVbhQ",
    "cost": 1004,
    "exposure": 120525,
    "reads": 3084,
    "interactions": 236,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "小花花🌸",
    "title": "小花花🌸｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/8B80dgn9RFP",
    "cost": 1152,
    "exposure": 728,
    "reads": 142,
    "interactions": 100,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "千亿",
    "title": "千亿｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/oxioTFrEBv",
    "cost": 1325,
    "exposure": 1959,
    "reads": 201,
    "interactions": 51,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "Feather girl",
    "title": "Feather girl｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9aYb5J4MdIP",
    "cost": 1051,
    "exposure": 13814,
    "reads": 4682,
    "interactions": 84,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "詹詹不是张张",
    "title": "詹詹不是张张｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/8GkXfpoDqRi",
    "cost": 1500,
    "exposure": 10710,
    "reads": 8120,
    "interactions": 199,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "圆小姐in HK（见过黄宗泽版）",
    "title": "圆小姐in HK（见过黄宗泽版）｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/69f768ac000000003601cde5?app_platform=ios&app_version=9.28.1&share_from_user_hidden=true&xsec_source=app_share&type=video&xsec_token=CBl5kcC1kZnQXMxBlhHAqivgGMU-boHKFUej54Zs7hh0U=&author_share=1&xhsshare=CopyLink&shareRedId=N0cyOUU6RkE6TEZFSko1Sj44QUk4NTtM&apptime=1777823295&share_id=428636efbfea4a2fa1dfcfed3fc17c9f",
    "cost": 1377,
    "exposure": 1194,
    "reads": 256,
    "interactions": 93,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "漪琳",
    "title": "漪琳｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/90rn5hPCU9U",
    "cost": 1850,
    "exposure": 909,
    "reads": 180,
    "interactions": 127,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "奶盖到处浪呀",
    "title": "奶盖到处浪呀｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/2FBeYlr7v1O",
    "cost": 1217,
    "exposure": 2464,
    "reads": 1154,
    "interactions": 170,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "小狼是我呀",
    "title": "小狼是我呀｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9KaAZnu5bQg",
    "cost": 1217,
    "exposure": 1357,
    "reads": 515,
    "interactions": 421,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "是熙熙麻麻吖",
    "title": "是熙熙麻麻吖｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9bPvLs7bODi",
    "cost": 16766,
    "exposure": 18208,
    "reads": 1942,
    "interactions": 184,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "5月投放笔记",
    "creator": "昱昱子",
    "title": "昱昱子｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/7dPSVVs1XPn",
    "cost": 2277,
    "exposure": 23360,
    "reads": 2887,
    "interactions": 217,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "养生小亿",
    "title": "养生小亿｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/33Nxbgssiom",
    "cost": 2790,
    "exposure": 91823,
    "reads": 6650,
    "interactions": 595,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "美美养生中",
    "title": "美美养生中｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/9FAw1QIbUGt",
    "cost": 2600,
    "exposure": 37024,
    "reads": 4810,
    "interactions": 666,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "不想上班的lulu",
    "title": "不想上班的lulu｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/4qXPjO1r8LM",
    "cost": 1100,
    "exposure": 4722,
    "reads": 585,
    "interactions": 14,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "摸带带鱼",
    "title": "摸带带鱼｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a292c67000000002101a14c?source=webshare&xhsshare=pc_web&xsec_token=ABCmjvQlyTp0iFzE9SLg-xDMm6lV3WEUBox3_caGMKPnw=&xsec_source=pc_share",
    "cost": 2000,
    "exposure": 81937,
    "reads": 24796,
    "interactions": 934,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "林林超会养",
    "title": "林林超会养｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/5vrIoC4J373",
    "cost": 3000,
    "exposure": 115761,
    "reads": 16168,
    "interactions": 1174,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "鑫心养生",
    "title": "鑫心养生｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/628igOtWnkU",
    "cost": 3200,
    "exposure": 43789,
    "reads": 5291,
    "interactions": 1553,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "渔村阿鸿",
    "title": "渔村阿鸿｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/5uHm4RZod7t",
    "cost": 2700,
    "exposure": 180977,
    "reads": 90918,
    "interactions": 2359,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "一帧的日记录",
    "title": "一帧的日记录｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/461E5L0n3h5",
    "cost": 2800,
    "exposure": 23277,
    "reads": 4327,
    "interactions": 368,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "瓜瓜的减脂日记",
    "title": "瓜瓜的减脂日记｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/7I9gwiMG2ZK",
    "cost": 2700,
    "exposure": 9608,
    "reads": 2711,
    "interactions": 308,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "石里原美",
    "title": "石里原美｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a27ff9c00000000210185d8?source=webshare&xhsshare=pc_web&xsec_token=CBEzMQQCJ_Pj4lkJyTMQ_EkKWy_WWJNvc-AuO2aQ_fbl8=&xsec_source=pc_share",
    "cost": 2880,
    "exposure": 196384,
    "reads": 45430,
    "interactions": 4022,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "石里原美",
    "title": "石里原美｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a315fb6000000002200a908?source=webshare&xhsshare=pc_web&xsec_token=CBrLqS1sM5_GHpFd88_lDUh8TU2otr_JnSPLG82D4CsHI=&xsec_source=pc_share",
    "cost": null,
    "exposure": null,
    "reads": null,
    "interactions": null,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "Lorraine在大湾区",
    "title": "Lorraine在大湾区｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a33762d0000000006033b2e?source=webshare&xhsshare=pc_web&xsec_token=CBMgDEY8JGfOzidNXdIUtTgA_SGWDeRAPnyXM8Hs2YRBw=&xsec_source=pc_share",
    "cost": 550,
    "exposure": 5247,
    "reads": 547,
    "interactions": 123,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "GG-",
    "title": "GG-｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a33538a0000000017028c9a?xsec_token=MBwTORz_opVcvST3HtE9yKn0HmdWWer3Ym79tOl8jvGmg=&xsec_source=pc_pgy",
    "cost": 2200,
    "exposure": 56664,
    "reads": 3654,
    "interactions": 427,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "Mindy敏",
    "title": "Mindy敏｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a3201940000000011018093?xsec_token=MBVZtset11-zZAvZaQ5w5oAzSYTDgMHsJNuWS69uR45pM=&xsec_source=pc_pgy",
    "cost": 1100,
    "exposure": 44371,
    "reads": 3725,
    "interactions": 455,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "尤克莉莉",
    "title": "尤克莉莉｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a31ffdb000000000f01e0cb?xsec_token=MBOKOQyup6fA54rSGAPN2h5hkDyim1yPh3iEuBXV0Xgpc=&xsec_source=pc_pgy",
    "cost": 770,
    "exposure": 57540,
    "reads": 4184,
    "interactions": 183,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "时乌安",
    "title": "时乌安｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a351f6e00000000060349f0?source=webshare&xhsshare=pc_web&xsec_token=CBNNRiiUVSHMJAICFsy_MnOnR6nYCRATHK8eoSHVlRb4M=&xsec_source=pc_share",
    "cost": 1200,
    "exposure": 18341,
    "reads": 3924,
    "interactions": 712,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "30岁的颜乔",
    "title": "30岁的颜乔｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a350509000000001101d262?source=webshare&xhsshare=pc_web&xsec_token=CBoWrdNjjFG5Li7VT6dNP9qRowUThQ9NjCW8GRQAeOeIA=&xsec_source=pc_share",
    "cost": 1200,
    "exposure": 13169,
    "reads": 2318,
    "interactions": 40,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "我没吃饱啊",
    "title": "我没吃饱啊｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a352fd0000000000f0332b2?source=webshare&xhsshare=pc_web&xsec_token=CBLQhDKG70WjM8p547h6yqxpkgCMRirldBMQnz0U4E9Q8=&xsec_source=pc_share",
    "cost": 1300,
    "exposure": 8176,
    "reads": 1571,
    "interactions": 148,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "乐乐麻麻育儿日记",
    "title": "乐乐麻麻育儿日记｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "http://xhslink.com/o/8SKzb6wOMoz",
    "cost": 1800,
    "exposure": 22938,
    "reads": 2792,
    "interactions": 149,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "Rani的香港省钱日记",
    "title": "Rani的香港省钱日记｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a33b252000000000702664b?source=webshare&xhsshare=pc_web&xsec_token=CBCAp3NRHVWzfw-yLeoveTE0sqX8Au_djJW_B4X3R_rns=&xsec_source=pc_share",
    "cost": 500,
    "exposure": 583,
    "reads": 61,
    "interactions": 25,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "MY.",
    "title": "MY.｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a33e6580000000007020baf?source=webshare&xhsshare=pc_web&xsec_token=CBNwKwfkMQdzuuEno-oqyfDdGMVSPFCMhx5zvwmWMDBiE=&xsec_source=pc_share",
    "cost": 800,
    "exposure": 1105,
    "reads": 166,
    "interactions": 144,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "神奇醋醋包",
    "title": "神奇醋醋包｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a351b1200000000080300fd?source=webshare&xhsshare=pc_web&xsec_token=CB4pxlxNggRsZcqjcl7ZZAkYgbbnzyTIICrAT2DF0hZoQ=&xsec_source=pc_share",
    "cost": 1000,
    "exposure": 2766,
    "reads": 691,
    "interactions": 56,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "张张肉肉",
    "title": "张张肉肉｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a33eca3000000001702b15e?source=webshare&xhsshare=pc_web&xsec_token=CB_A124vsJai-7q5DBSx3CrUOO7MCLm1Ww-mnk_2W2ySo=&xsec_source=pc_share",
    "cost": 1200,
    "exposure": 5649,
    "reads": 1644,
    "interactions": 350,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "香港小包",
    "title": "香港小包｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a35326a0000000007013d97?source=webshare&xhsshare=pc_web&xsec_token=CBMk60ptE3Hq4WKe9KiRKcE0Hyw2w_ThiHBVTmIf4kjis=&xsec_source=pc_share",
    "cost": 750,
    "exposure": 4140,
    "reads": 1687,
    "interactions": 101,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "肖恩爱旅行",
    "title": "肖恩爱旅行｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a33e5c60000000006023376?source=webshare&xhsshare=pc_web&xsec_token=CBj8nzSI5YWFNAuhDK6ex2nu16FtrhPRx8TES3jAKOpGI=&xsec_source=pc_share",
    "cost": 800,
    "exposure": 24232,
    "reads": 2640,
    "interactions": 105,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "香港曼迪",
    "title": "香港曼迪｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a3395d00000000021016b65?source=webshare&xhsshare=pc_web&xsec_token=CBiP4SYlJLCOiXv5vDOkwVJ07NlwOxfO1b9ObNhrv8D0Q=&xsec_source=pc_share",
    "cost": 3000,
    "exposure": 6888,
    "reads": 5425,
    "interactions": 314,
    "status": "已导入Excel数据"
  },
  {
    "project": "公牛牌风痛灵",
    "brand": "公牛牌",
    "batch": "6-7月投放笔记",
    "creator": "Amy在香港",
    "title": "Amy在香港｜公牛牌风痛灵种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/discovery/item/6a348547000000000702295f?source=webshare&xhsshare=pc_web&xsec_token=CBEIUwnXVKNv29kdW6KP7mAvAIKmW0x-lc_TViufRJQkA=&xsec_source=pc_share",
    "cost": 800,
    "exposure": 1409,
    "reads": 299,
    "interactions": 165,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "小鬼_Asen",
    "title": "小鬼_Asen｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2a9968000000002201bc90?xsec_token=MBSGQZxOLBN3SeY2JJcbLxcYYsHloagKzrChC36iBNQPs=&xsec_source=pc_pgyexport",
    "cost": 880,
    "exposure": 21537,
    "reads": 3867,
    "interactions": 144,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "豚豚子",
    "title": "豚豚子｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2a6d0a0000000006021e30?xsec_token=MBSGQZxOLBN3SeY2JJcbLxcVqpswgu8L-Nv4nVCXav8yg=&xsec_source=pc_pgyexport",
    "cost": 902,
    "exposure": 8027,
    "reads": 1258,
    "interactions": 37,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "小妮在摸鱼",
    "title": "小妮在摸鱼｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2a48df000000000702b86c?xsec_token=MBSGQZxOLBN3SeY2JJcbLxccbyx-gYDX4FrS2Qoy3ZpUg=&xsec_source=pc_pgyexport",
    "cost": 880,
    "exposure": 35526,
    "reads": 4608,
    "interactions": 346,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "是你的星崽（班郁版",
    "title": "是你的星崽（班郁版｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2a3f78000000001503ed76?xsec_token=MBSGQZxOLBN3SeY2JJcbLxcUXUIc1LKmtrq7sBlZ8s4A4=&xsec_source=pc_pgyexport",
    "cost": 880,
    "exposure": 7415,
    "reads": 1252,
    "interactions": 166,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "影儿老师",
    "title": "影儿老师｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2a365b00000000070268eb?xsec_token=MBSGQZxOLBN3SeY2JJcbLxcV74KcbamDBhpgHisy8UVYw=&xsec_source=pc_pgyexport",
    "cost": 660,
    "exposure": 9436,
    "reads": 1122,
    "interactions": 38,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "李世榕",
    "title": "李世榕｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2a60fe0000000035023d65?xsec_token=MBSGQZxOLBN3SeY2JJcbLxcTyxru6J2s3IurroUIMzcNc=&xsec_source=pc_pgyexport",
    "cost": 1100,
    "exposure": 23605,
    "reads": 5524,
    "interactions": 879,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "COCO姐的旅行日记",
    "title": "COCO姐的旅行日记｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2974c4000000002003b400?xsec_token=MBaLScj7fQQ_lQTBcycY5hAkQ0bFn1yRKo7P6nPqbyKwA=&xsec_source=pc_pgyexport",
    "cost": 658,
    "exposure": 1236,
    "reads": 129,
    "interactions": 37,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "花园里没有菜",
    "title": "花园里没有菜｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a292b280000000022019263?xsec_token=MBaLScj7fQQ_lQTBcycY5hAsqtEjnCCoIth0rS2N7nvPg=&xsec_source=pc_pgyexport",
    "cost": 990,
    "exposure": 6260,
    "reads": 730,
    "interactions": 84,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "pe哭酱🤩",
    "title": "pe哭酱🤩｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a290c71000000001c0262c2?xsec_token=MBaLScj7fQQ_lQTBcycY5hAt0por_UpkgZLfzGrP3LYBI=&xsec_source=pc_pgyexport",
    "cost": 935,
    "exposure": 62800,
    "reads": 14792,
    "interactions": 501,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "苗苗旅行日记本",
    "title": "苗苗旅行日记本｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a291d0c0000000020039317?xsec_token=MBaLScj7fQQ_lQTBcycY5hAiCSkVccZ4yNy8RdQ1Co_Ag=&xsec_source=pc_pgyexport",
    "cost": 825,
    "exposure": 13260,
    "reads": 2229,
    "interactions": 336,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "小上同学",
    "title": "小上同学｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a28e7e10000000008002b6c?xsec_token=MBJxBfH7CIKfvZWYfj61a6i9Yp4JTt7U8wez6nfCWtT8Q=&xsec_source=pc_pgyexport",
    "cost": 990,
    "exposure": 19958,
    "reads": 2612,
    "interactions": 142,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "国家高级游泳教练丹尼",
    "title": "国家高级游泳教练丹尼｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a28f03f000000003502f596?xsec_token=MBJxBfH7CIKfvZWYfj61a6i4YpqjRr-AYYcvyToDCz_0s=&xsec_source=pc_pgyexport",
    "cost": 968,
    "exposure": 6027,
    "reads": 1288,
    "interactions": 148,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "爱跑步的刘锅文",
    "title": "爱跑步的刘锅文｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a27eba4000000002202bb9e?xsec_token=MB3JEybhlesoUTbib-UQFBPpw83Hz6YYOTpi4s13Z9fPw=&xsec_source=pc_pgyexport",
    "cost": 660,
    "exposure": 2037,
    "reads": 239,
    "interactions": 20,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "大油油 you🌿",
    "title": "大油油 you🌿｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a263823000000002003ad70?xsec_token=MBl74-Xxs_DDTXkW1jEn7AV0lg1z9ZI3B9POGyogLd0B4=&xsec_source=pc_pgyexport",
    "cost": 866,
    "exposure": 13637,
    "reads": 2339,
    "interactions": 94,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "6-7月投放笔记",
    "creator": "大峰来咯",
    "title": "大峰来咯｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/6a2639bf000000001702952c?xsec_token=MBl74-Xxs_DDTXkW1jEn7AVw4OMMPg9xQRCm_4Cwg4Rww=&xsec_source=pc_pgyexport",
    "cost": 988,
    "exposure": 8898,
    "reads": 1243,
    "interactions": 158,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "許言午",
    "title": "許言午｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69fd28e900000000380356de?xsec_token=MBrBr_NbNVAoL14Tbu9mldynlwvFdKyuUrGP9HLh6NbGs=&xsec_source=pc_pgyexport",
    "cost": 330,
    "exposure": 10705,
    "reads": 1744,
    "interactions": 491,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "蒋不了道理（重回厂妹版）",
    "title": "蒋不了道理（重回厂妹版）｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69fc73060000000035020575?xsec_token=MBUP6VEpsQQq1TNPrJErMa6pu50XBWFOmm5LVohV-nZgw=&xsec_source=pc_pgyexport",
    "cost": 440,
    "exposure": 22510,
    "reads": 3681,
    "interactions": 105,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "薄荷养生记",
    "title": "薄荷养生记｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69fc260400000000360330c4?xsec_token=MBUP6VEpsQQq1TNPrJErMa6igwQh8HhKDJwCAhnumQEsw=&xsec_source=pc_pgyexport",
    "cost": 396,
    "exposure": 3386,
    "reads": 1325,
    "interactions": 89,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "格林学姐",
    "title": "格林学姐｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69fc2b5300000000380376c7?xsec_token=MBUP6VEpsQQq1TNPrJErMa6hjsm05eCEnp-wfhquVWbL0=&xsec_source=pc_pgyexport",
    "cost": 550,
    "exposure": 1708,
    "reads": 339,
    "interactions": 14,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "小陈在养生",
    "title": "小陈在养生｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69fb1299000000001e00c265?xsec_token=MBwPIozb_v_pCOjiHjDc669Zjpi7Rxb4u3t7pHhXkFgWM=&xsec_source=pc_pgyexport",
    "cost": 330,
    "exposure": 3461,
    "reads": 760,
    "interactions": 108,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "五姐很忙",
    "title": "五姐很忙｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69f9e9600000000036033c2a?xsec_token=MB-ARDdRxDW7Ti1SgCIu5MpYbjJudQDCDZi6gP0sd_zkU=&xsec_source=pc_pgyexport",
    "cost": 550,
    "exposure": 5107,
    "reads": 680,
    "interactions": 176,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "莲的慢生活",
    "title": "莲的慢生活｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69f49318000000003502ee24?xsec_token=MB-maZrqXsXchrup0kJcSNiI1HuWPb37Zj9gcl_niJTjQ=&xsec_source=pc_pgyexport",
    "cost": 385,
    "exposure": 8976,
    "reads": 1161,
    "interactions": 325,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "啊包在香港",
    "title": "啊包在香港｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69f4ec63000000003701ef64?xsec_token=MB-maZrqXsXchrup0kJcSNiEiPwHAxm5c3Wgh2AkvBhC0=&xsec_source=pc_pgyexport",
    "cost": 660,
    "exposure": 1848,
    "reads": 277,
    "interactions": 10,
    "status": "已导入Excel数据"
  },
  {
    "project": "济众堂百步追风活络油",
    "brand": "济众堂",
    "batch": "5月投放笔记",
    "creator": "小花瘦身养生中",
    "title": "小花瘦身养生中｜济众堂百步追风活络油种草笔记",
    "platform": "小红书",
    "link": "https://www.xiaohongshu.com/explore/69f48426000000002301c242?xsec_token=MB-maZrqXsXchrup0kJcSNiMG9plKnImQ6akwPVWTD9eI=&xsec_source=pc_pgyexport",
    "cost": 407,
    "exposure": 5525,
    "reads": 781,
    "interactions": 159,
    "status": "已导入Excel数据"
  }
]
;

export const risks = [
  {
    level: "red",
    title: "万宁销量数据未建立反馈机制",
    desc: "活络油进入万宁销量考核期，但万宁销量反馈机制仍需建立。",
    impact: "影响月销10万元目标跟踪和资源判断。",
    action: "建立万宁销量数据反馈节奏。"
  },
  {
    level: "yellow",
    title: "电商数据未建立反馈机制",
    desc: "淘宝、京东及小红书店铺数据尚未形成固定回传。",
    impact: "影响线上电商增长判断。",
    action: "确认电商数据口径和更新周期。"
  },
  {
    level: "yellow",
    title: "达人/兼职费用待结算",
    desc: "达人费用和兼职费用需要确认结算。",
    impact: "影响达人合作推进和执行稳定性。",
    action: "确认费用结算时间。"
  },
  {
    level: "red",
    title: "保健食品资质未完成",
    desc: "香港相关资质、内地备案、产品资质、社媒报白资料尚未完成。",
    impact: "影响肝轻松、眼清清上市进度。",
    action: "确认资质责任人与推进时间。"
  },
  {
    level: "yellow",
    title: "小红书店铺资质待确认",
    desc: "小红书店铺承接及投流相关资质仍需确认。",
    impact: "影响线上转化承接和投流测试。",
    action: "补齐资质清单并逐项确认。"
  },
  {
    level: "yellow",
    title: "京东主体投放路径待沟通",
    desc: "京东主体是否可承接投放路径仍需沟通。",
    impact: "影响后续电商转化链路选择。",
    action: "确认京东主体与投放路径。"
  }
];

export const supportItems = [
  {
    priority: "P1",
    title: "达人/兼职费用结算",
    project: "公牛牌风痛灵 / 整体项目",
    decision: "确认达人费用和兼职费用结算时间与流程。",
    impact: "影响后续达人合作与执行稳定性。"
  },
  {
    priority: "P0",
    title: "万宁资源推进",
    project: "济众堂百步追风活络油",
    decision: "确认是否协助争取万宁推广资源、广告位资源、其他渠道资源。",
    impact: "影响月销10万元考核期的渠道支持。"
  },
  {
    priority: "P1",
    title: "京东主体确认",
    project: "济众堂保健食品",
    decision: "确认京东主体是否可作为后续电商承接路径。",
    impact: "影响线上电商增长链路。"
  },
  {
    priority: "P0",
    title: "保健食品资质支持",
    project: "济众堂保健食品",
    decision: "确认香港相关资质、内地备案、报白资料推进负责人和时间。",
    impact: "影响肝轻松、眼清清上市进度。"
  }
];
